### ISSUE TITLE
plugin crashes in new IDEA

### ISSUE THREAD

**Issue by magicprinc** [edgafner/GBrowser#226]
IntelliJ IDEA 2023.3.5 (Ultimate Edition)
Build #IU-233.14808.21, built on March 12, 2024
Runtime version: 17.0.10+1-b1087.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  analyze.exceptions.on.the.fly=true
  documentation.show.toolbar=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.paperetto.dash (3.3)
  com.nasller.CodeGlancePro (1.8.1)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  com.gafner.giv (2024.1.13)
  com.intellij.ideolog (222.3.2.0)
  com.intellij.grazie.pro (0.3.290)
  org.jetbrains.jumpToLine (0.1.15)
  ink.organics.pojo2json (2.0.5)
  GsonFormatPlus (1.6.1)
  com.intellij.datagen (233.13135.65)
  org.avaje.ebean11.enhancer (13.26.0)
  VisualVMLauncher (1.23.1-IJ2023.3)
  String Manipulation (9.12.0)
  com.intellij.microservices.debugger (233.13135.65)
  org.asciidoctor.intellij.asciidoc (0.41.8)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-233)
  fr.jukien.intellij.plugins.pojo-generator (2.5.0)
  com.intellij.bigdatatools.core (233.14808.21)
  com.bruce.intellijplugin.generatesetter (2.8.4)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.jetbrains.packagesearch.intellij-plugin (233.11800.8)
  com.haulmont.jpab (2023.4.1-233)
  com.sourcegraph.jetbrains (5.3.3914)
  com.jetbrains.writerside (2024.01.233.14389)
  com.intellij.bigdatatools.kafka (233.13135.103)
  com.intellij.java.rareRefactorings (233.11799.196)
Kotlin: 233.14808.21-IJ

```
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/toolbarLayout/ToolbarLayoutStrategy
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar.createToolBarAction(GBrowserToolWindowActionBar.kt:152)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar.access$createToolBarAction(GBrowserToolWindowActionBar.kt:31)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar$browserComponent$2.invoke(GBrowserToolWindowActionBar.kt:52)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar$browserComponent$2.invoke(GBrowserToolWindowActionBar.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar.getBrowserComponent(GBrowserToolWindowActionBar.kt:46)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowActionBar.<init>(GBrowserToolWindowActionBar.kt:74)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowBrowser.<init>(GBrowserToolWindowBrowser.kt:25)
	at com.github.gbrowser.util.GBrowserToolWindowUtil.createContentTab(GBrowserToolWindowUtil.kt:33)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowFactory.createToolWindowContent(GBrowserToolWindowFactory.kt:43)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:594)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:573)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1035)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:969)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:672)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:641)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2244)
	at com.intellij.toolWindow.StripeButton._init_$lambda$0(StripeButton.kt:62)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:411)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at com.intellij.toolWindow.StripeButton.processMouseEvent(StripeButton.kt:247)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.actionSystem.toolbarLayout.ToolbarLayoutStrategy PluginClassLoader(plugin=PluginDescriptor(name=GBrowser, id=com.gafner.giv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\GBrowser, version=2024.1.13, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 74 more
```

**Comment by Jonatha1983** [comment]
Yeah I remove the latest version and released a new one for the upcoming 241.

I hope I ll find the time to fix this issue this week and release a version for previous IDE versions 

@magicprinc Thanks for reporting and sorry about it
