### ISSUE TITLE
[BUG]: Exception on click hyperlink

### ISSUE THREAD

**Issue by qsef1256** [edgafner/GBrowser#340]
The error below occurs every time I click on a hyperlink on a webpage.

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#8452,Thread-6906,5,main] 1743120097 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#114,AWT-EventQueue-0,6,main] 807534437
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:209)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:78)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:274)
	at com.intellij.openapi.wm.impl.content.SingleContentSupplier$Companion.getSupplierFrom(SingleContentSupplier.kt:112)
	at com.intellij.openapi.wm.impl.content.SingleContentSupplier$Companion.getSupplierFrom(SingleContentSupplier.kt:109)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.getSupplier(SingleContentLayout.kt:84)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.tryUpdateContentView(SingleContentLayout.kt:101)
	at com.intellij.openapi.wm.impl.content.SingleContentLayout.update(SingleContentLayout.kt:72)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.update(ToolWindowContentUi.java:364)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.updateContentUi(ToolWindowImpl.kt:623)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowFactory.addSettingsListener$lambda$3(GBrowserToolWindowFactory.kt:118)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy12/jdk.proxy12.$Proxy292.onSettingsChange(Unknown Source)
	at com.github.gbrowser.services.GBrowserService.addHistory(GBrowserService.kt:613)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowBrowser.setHistoryItem(GBrowserToolWindowBrowser.kt:174)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowBrowser.onAddressChange(GBrowserToolWindowBrowser.kt:214)
	at com.github.gbrowser.ui.gcef.impl.GBrowserCefDisplayChangeHandler.onAddressChange(GBrowserCefDisplayChangeHandler.kt:14)
	at jcef/org.cef.CefClient.onAddressChange(CefClient.java:424)
```

## Versions

GBrowser: 2024.3.3
IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Memory: 2048M
Cores: 12
Kotlin: 243.21565.193-IJ

**Comment by Jonatha1983** [comment]
Thanks for reporting I ll take a look
