### ISSUE TITLE
[BUG]: GBrowser won't start with Android Studio (the IDE is based on InteliJ) JCEF error

### ISSUE THREAD

**Issue by cedricferry** [edgafner/GBrowser#352]
**Describe the bug**
GBrowser won't start with Android Studio (the IDE is based on InteliJ) and throw exception about JCEF.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://developer.android.com/studio and download the IDE
2.  Install the GBrowser plugin (Settings/Preferences > Plugins > Marketplace > Search for GBrowser > Install Plugin)
3. Open GBrowser in the panel (View > Tools Window > GBrowser
4. Panel is empty and get the following exception about JCEF
```
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:210)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:172)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:36)
	at com.github.gbrowser.ui.gcef.GCefBrowser.<init>(GCefBrowser.kt:34)
	at com.github.gbrowser.ui.gcef.GCefBrowser.<init>(GCefBrowser.kt:30)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowBrowser.<init>(GBrowserToolWindowBrowser.kt:28)
	at com.github.gbrowser.util.GBrowserToolWindowUtil.createContentTab(GBrowserToolWindowUtil.kt:33)
	at com.github.gbrowser.ui.toolwindow.gbrowser.GBrowserToolWindowFactory.createToolWindowContent(GBrowserToolWindowFactory.kt:43)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:667)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:646)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1036)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:970)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:670)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:628)
	at com.intellij.ide.actions.ActivateToolWindowAction.actionPerformed(ActivateToolWindowAction.kt:157)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:345)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks$lambda$4(ActionUtil.kt:316)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1168)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.kt:315)
	at com.intellij.platform.ide.menu.MacNativeActionMenuItemKt.performAction$lambda$1(MacNativeActionMenuItem.kt:134)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:231)
	at com.intellij.platform.ide.menu.MacNativeActionMenuItemKt.performAction(MacNativeActionMenuItem.kt:128)
	at com.intellij.platform.ide.menu.MacNativeActionMenuItemKt.access$performAction(MacNativeActionMenuItem.kt:1)
	at com.intellij.platform.ide.menu.MacNativeActionMenuItem.menuItemPeer$lambda$3$lambda$2$lambda$1$lambda$0(MacNativeActionMenuItem.kt:51)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.platform.ide.menu.MacNativeActionMenuItem.menuItemPeer$lambda$3$lambda$2$lambda$1(MacNativeActionMenuItem.kt:50)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Expected behavior**
Browser should show

**Screenshots**
<img width="1771" alt="Screenshot 2024-11-28 at 9 48 07 pm" src="https://github.com/user-attachments/assets/b096df7d-7b67-4dc7-b0ab-f993c50dcc3b">

**Desktop (please complete the following information):**
- OS: macOS
- Version: 15.1.1 (Sequoia)

**Jetrbrains IDE (please complete the following information):**
- IDE: Android Studio Lady Bug (2024.2.1) / Android Studio Koala (2024.1.2)
- Version: 2024.2.1 & 2024.1.2

**Additional context**
 * this is likely related to a custom "Boot Java Runtime for the IDE" that doesn't contains JCEF.

you can detect if JCEF is available with `JBCefApp.isSupported()`

https://plugins.jetbrains.com/docs/intellij/jcef.html#using-jcef-in-a-plugin
 
You could consider adding a verification that JCEF is available and direct the user to choosing the right JR with JCEF
https://stackoverflow.com/questions/69171807/markdown-editor-and-preview-not-working-in-android-studio

**Comment by Jonatha1983** [comment]
Hi @cedricferry,

Unfortunately, Android Studio doesn't work with the JetBrains JDK required for JCEF, as explained here: https://platform.jetbrains.com/t/implementing-webview-toolwindows-in-android-studio/684.

Given that this plugin relies entirely on JetBrains JCEF, I'll need to remove Android Studio support.

I understand this is disappointing, and I apologize for the issue.
